/**
 * This source file was generated by the Gradle 'init' task
 * @author Alexander Mychlo
 */
package org.example;

public class App {
    /**
     * 
     * @return "Hello World!"
     */
    public String getGreeting() {
        return "Hello World!";
    }

    /**
     * Main entry point
     */
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
